### ISSUE TITLE
The lang_us field for locate.msg needs updated

### ISSUE THREAD

**Issue by Tarig0** [ForgeEssentials/FELocalizations#14]
currently throws an error corrected key below

%s is at %d, %d, %d in dim %d with gamemode %s

**Comment by helinus** [comment]
There is more to it then that...
This is the error: https://gist.github.com/helinus/75b2fceb7cfd29b16e1b
Link to locale: https://github.com/ForgeEssentials/FELocalizations/blob/master/en_US.xml#L281
Link to code: https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/master/src/FE_SRC_COMMON/com/ForgeEssentials/commands/CommandLocate.java#L67

**Comment by helinus** [comment]
Nope: https://gist.github.com/helinus/7c9baffdf9f41ea83110

**Comment by helinus** [comment]
it's now fixed
