### ISSUE TITLE
Typos in en_US.xml

### ISSUE THREAD

**Issue by jovino** [ForgeEssentials/FELocalizations#4]
Localization file en_US.xml key "&lt;message.auth.error.notregisterred&gt;" is incorrect. Should be "%s is not registered!"

Localization file en_US.xml key "&lt;message.auth.error.notregisterred&gt;" is incorrect. Should be "%s is already registered!"

Localization file en_US.xml key "&lt;command.register.register&gt;" is incorrect. Should be "You have been registered. Use /login &lt;pwd>"

Localization file en_US.xml key "&lt;command.serversettings.info.console&gt;" is incorrect. Should be "Change or view the server settings (server.properties)"

Localization file en_US.xml key "&lt;command.serversettings.info.player&gt;" is incorrect. Should be "Change or view the server settings (server.properties)"

**Comment by AbrarSyed** [comment]
fixed 298c097efb2933271a0fd01294273e07ca471fbc
