### ISSUE TITLE
some en_US.xml keys are wrong "Localization"

### ISSUE THREAD

**Issue by JamieKG** [ForgeEssentials/FELocalizations#5]
Localization file en_US.xml key "message.auth.error.notregisterred" is listed twice
Localization file en_US.xml key "message.auth.needRegister" is listed twice I think its a typo and one should be "message.auth.needlogin"

**Comment by AbrarSyed** [comment]
fixed 2acfefead64fa45f3999e70ee3f517f53ed4ff55
